export const NOTE_NAME_C = 'NOTE_NAME/NOTE_NAME_C';

export const NOTE_NAME_C_SHARP = 'NOTE_NAME/NOTE_NAME_C_SHARP';
export const NOTE_NAME_D_FLAT = 'NOTE_NAME/NOTE_NAME_D_FLAT';

export const NOTE_NAME_D = 'NOTE_NAME/NOTE_NAME_D';

export const NOTE_NAME_D_SHARP = 'NOTE_NAME/NOTE_NAME_D_SHARP';
export const NOTE_NAME_E_FLAT = 'NOTE_NAME/NOTE_NAME_E_FLAT';

export const NOTE_NAME_E = 'NOTE_NAME/NOTE_NAME_E';

export const NOTE_NAME_F = 'NOTE_NAME/NOTE_NAME_F';

export const NOTE_NAME_F_SHARP = 'NOTE_NAME/NOTE_NAME_F_SHARP';
export const NOTE_NAME_G_FLAT = 'NOTE_NAME/NOTE_NAME_G_FLAT';

export const NOTE_NAME_G = 'NOTE_NAME/NOTE_NAME_G';

export const NOTE_NAME_G_SHARP = 'NOTE_NAME/NOTE_NAME_G_SHARP';
export const NOTE_NAME_A_FLAT = 'NOTE_NAME/NOTE_NAME_A_FLAT';

export const NOTE_NAME_A = 'NOTE_NAME/NOTE_NAME_A';

export const NOTE_NAME_A_SHARP = 'NOTE_NAME/NOTE_NAME_A_SHARP';
export const NOTE_NAME_B_FLAT = 'NOTE_NAME/NOTE_NAME_B_FLAT';

export const NOTE_NAME_B = 'NOTE_NAME/NOTE_NAME_B';