export const NUMBER_ONE = 'NUMBER/NUMBER_ONE';

export const NUMBER_ONE_SHARP = 'NUMBER/NUMBER_ONE_SHARP';
export const NUMBER_TWO_FLAT = 'NUMBER/NUMBER_TWO_FLAT';

export const NUMBER_TWO = 'NUMBER/NUMBER_TWO';

export const NUMBER_TWO_SHARP = 'NUMBER/NUMBER_TWO_SHARP';
export const NUMBER_THREE_FLAT = 'NUMBER/NUMBER_THREE_FLAT';

export const NUMBER_THREE = 'NUMBER/NUMBER_THREE';

export const NUMBER_FOUR = 'NUMBER/NUMBER_FOUR';

export const NUMBER_FOUR_SHARP = 'NUMBER/NUMBER_FOUR_SHARP';
export const NUMBER_FIVE_FLAT = 'NUMBER/NUMBER_FIVE_FLAT';

export const NUMBER_FIVE = 'NUMBER/NUMBER_FIVE';

export const NUMBER_FIVE_SHARP = 'NUMBER/NUMBER_FIVE_SHARP';
export const NUMBER_SIX_FLAT = 'NUMBER/NUMBER_SIX_FLAT';

export const NUMBER_SIX = 'NUMBER/NUMBER_SIX';

export const NUMBER_SIX_SHARP = 'NUMBER/NUMBER_SIX_SHARP';
export const NUMBER_SEVEN_FLAT = 'NUMBER/NUMBER_SEVEN_FLAT';

export const NUMBER_SEVEN = 'NUMBER/NUMBER_SEVEN';